version: 0.2

phases:
  install:
    commands:
      - echo Installing frontend dependencies...
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building Angular frontend...
      - ng build --prod
      - cd ../backend
      - echo Packaging Spring Boot backend...
      - mvn clean package
      - cp -r ../frontend/dist/* src/main/resources/static/
      - mvn package
artifacts:
  files:
    - backend/target/ROOT.war
