version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # or the version your Angular project uses
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - cd frontend
      - ng build --prod
artifacts:
  files:
    - frontend/dist/**/*
