version: 0.2

env:
  variables:
    NODE_OPTIONS: "--openssl-legacy-provider"

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm ci
      - cd ..
      - echo "Installing backend dependencies"
      - cd backend
      - ./mvnw clean install -DskipTests
      - cd ..

  build:
    commands:
      - echo "Building Angular frontend"
      - cd frontend
      - ng build --prod
      - cd ..
      - echo "Copying frontend build to Spring Boot static folder"
      - cp -r frontend/dist/* backend/src/main/resources/static/
      - echo "Building Spring Boot backend WAR"
      - cd backend
      - ./mvnw clean package
      - cd ..

artifacts:
  files:
    - backend/target/ROOT.war
