name: Test Deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} # Indented 2 spaces
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }} # Indented 2 spaces

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Get current date and time
        id: datetime
        run: echo "now=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
    
      - name: Slack Notification - Start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Deployment started on AZURE TEST SERVER on ${{ steps.datetime.outputs.now }} by ${{ github.actor }}. Testing sample notification."
            }

      - name: Create Deployment
        uses: bobheadxi/deployments@v1
        with:
          step: start
          env: test
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish Deployment
        if: always()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          status: ${{ job.status }}
          env: test
          token: ${{ secrets.GITHUB_TOKEN }}
